### ISSUE TITLE
Save option on Deploy page should mention where the Ansible settings will be stored

### ISSUE THREAD

**Issue by gsternagl** [red-hat-storage/cockpit-ceph-installer#41] opened 2019-11-22 09:58 UTC
When using the "Save" option on page "6. Deploy the Cluster" it should be mentioned where Ansible files actually get saved to so that they can be reused, archived, etc. 

RFE: Ideally we could scan that last saved information and pre-populate the cockpit-ceph-installer forms with that information when used again.

**Comment by pcuzner** [comment] 2019-11-27 22:58
patch in the sudo-support branch

**Comment by pcuzner** [comment] 2019-12-11 04:16
fixed in 0-9.7. Closing. Re-open if the issue is not resolved.

**Closed as completed by pcuzner** 2019-12-11 04:16 UTC
Labels: enhancement
