### ISSUE TITLE
installer hangs when executing ceph-ansible configure firewall task

### ISSUE THREAD

**Issue by gsternagl** [red-hat-storage/cockpit-ceph-installer#42] opened 2019-11-25 09:44 UTC
I have disabled firewalld completely and this seems to make the installer to hang during the stage when it tries to configure the firewall. 

BUG (tbv): when a ceph-ansible task hangs like e.g. my firewall configure task did, a user is attempted to reload the web-page. But that will start the cockpit-installer from scratch again (screen #1) allthough ansible is still running in the background. 

RFE: It would be good to expose the ceph-ansible option to enable/disable firewall configuration in the installer

**Comment by pcuzner** [comment] 2019-11-27 23:02
OK. So on the environment page we can have a check box, that's ticked by default for firewall enabled. And if unchecked we add configure_firewall: False to all.yml

Does that cover it?
@gsternagl

**Comment by gsternagl** [comment] 2019-11-28 07:46
Absolutely! Thanks.

**Comment by pcuzner** [comment] 2019-12-11 04:15
fixed in 0-9.7. Closing. Re-open if the issue is not resolved.

**Closed as completed by pcuzner** 2019-12-11 04:15 UTC
Labels: enhancement
